routes/web.php
<?php

use App\User;
 
Auth::routes();

Route::get('/d' , function(){
  
    $collection = (new App\AnswerParam)
    ->where('param_id',15)
    ->where('value','like',"'%")
    ->get() ; //->find(2)->toArray();
    //dd($collection);
    
    foreach( $collection as $answer_param  ){
         
      //  $answer_param->value = json_encode(walker($answer_param->value));
        
       // $answer_param->save();
    }
 dd($collection);
    dd(url('/') );
    $c = new App\Http\Controllers\DuplicateProcedureController();

    $answer = App\Answer::find(12260);
    $new_answer = new App\Answer;
    $new_answer->title = "test";
    $new_answer->save();

    $c->duplicateAnswerParamsAndAssociate($answer, $new_answer);
    //dd($new_answer->params()->withPivot('value'));
    
});
 Route::get('/test-me',  function(){
  //DB::enableQueryLog();
 
//$id= 25;
//$c=       App\Client::find($id);
// dd(DB::getQueryLog());
   dd('$c');
 });
Route::middleware(['auth'])->group(function () {
    #Home
    Route::get('/', 'HomeController@index');
    Route::get('home', 'HomeController@index')->name('home');
});
     

 //Route::group(['middleware' => 'auth:api'], function () {
      Route::get('run-beta-teach/{procedure}', 'RedirectController@runBetaTeach')->name('procedures.beta-teach');
 //});
Route::middleware(['doctor'])->group(function () {
    #Home
    Route::get('run-pdf/{test_id}', 'RedirectController@runPdf')->name('user.pdf-report');
    Route::get('run-report/{test_id}', 'RedirectController@runReport')->name('user.test-report');
    Route::get('home/doctor', 'HomeDoctorController@index')->name('home.doctor');
    Route::get('run-procedure/{procedure}', 'RedirectController@runTest')->name('procedures.run');
    Route::get('run-teach/{procedure}', 'RedirectController@runTeach')->name('procedures.teach');
    Route::get('run-beta-teach/{procedure}', 'RedirectController@runBetaTeach')->name('procedures.beta-teach');
    Route::get('run-beta-new-teach/{procedure}', 'RedirectController@runBetaNewTeach')->name('procedures.beta-new-teach');
    Route::get('run-combination/{combination}', 'RedirectController@runCombination')->name('combination.run');
    Route::get('run-unfinished-combination/{test_id}', 'RedirectController@runUnfinishedCombination')->name('combination.unfinished.run');
    
});

Route::middleware(['supervisor'])->group(function () {

    #Home
    Route::get('home/supervisor', 'HomeSupervisorController@index')->name('home.supervisor');
     Route::get('home/supervisor/procedures', 'RedirectController@runProceduresPage')->name('procedures_page.run');
    #Procedures Abbreviations
    Route::get('procedures-abbreviations/{category_id}', 'ProceduresAbbreviationController@index')
        ->name('procedures-abbreviations.index');
     Route::post('procedures/set-temp-category/{procedure}', 'ProceduresAbbreviationController@setTempCategory');
     Route::post('procedures/set-temp-category/{procedure}/undo', 'ProceduresAbbreviationController@setTempCategory');
     #Set Procedures/Combinations to temp
     Route::post('combinations/set-temp-category/{combination}', 'TempController@setTempCategory');
     Route::post('combinations/set-temp-category/{combination}/undo', 'TempController@setTempCategory');
       

    #Production Link
    Route::get('production-link/{type}/{id}', 'ProductionLinkController')->name('production-link');

    #Client Reports
    Route::get('client-reports/{client}', 'ClientsReportsController@init')->name('client-reports');
    Route::get('client-reports/{client}/{connection}/{unapproved?}/{today?}', 'ClientsReportsController@index');
    Route::get('client-reports/link/{test}', 'ClientsReportsController@makeLink');
    Route::get('new-client-reports/{client_id}/{connection}/not-approved', 'ClientsReportsController@notApproved');

    #Client Statistics
    Route::get('client-statistics/{client}', 'ClientsStatisticsController@index')->name('client-statistics');
    Route::get('client-statistics/{client}/procedures', 'ClientsStatisticsController@procedures');
    Route::get('client-statistics/{client}/reports-count', 'ClientsStatisticsController@getReportsCount');

    #Client Referrals
    Route::get('client-referrals', 'ClientReferralsController@index')->name('client-referrals');

    #Client Decisions
    Route::post('client-decisions', 'ClientDecisionsController@store');
    Route::get('client-decisions', 'ClientDecisionsController@index');

    #client Physicians
    Route::get('client-physicians/{physician}', 'ClientPhysicianController@index');

    #Tests
    Route::get('test', 'TestsController@index')->name('tests.index');
    Route::delete('test/{id}', 'TestsController@destroy')->name('tests.destroy');
    #CountTests
    Route::get('count-tests/{from}/{to}/{group?}/{physician?}', 'CountTestsController@index')
        ->name('count-tests.index');

    #procedures
    Route::get('procedures', 'ProceduresController@index')->name('procedures.index');
    Route::get('procedures-list', 'ProceduresController@index');//->name('procedures.index'); //for json!
});

Route::middleware(['admin'])->group(function () {

    #home
    Route::get('home/admin', 'HomeAdminController@index')->name('home.admin');

    #Client
    Route::resource('clients', 'ClientsController');

    #Track Changes
    Route::resource('track-changes', 'TrackChangeController');

    #Answer Groups
    Route::resource('answer-groups', 'AnswerGroupsController');
    Route::get('display-groups/{question}', 'DisplayGroupsController@index')->name('display-groups.index');
    
    #Display Groups
    Route::resource('display-groups', 'DisplayGroupController');
    Route::get('answer-group/display-groups/{displayGroup}', 'DisplayGroupController@answerGroup');
    Route::get('question/display-groups/{displayGroup}', 'DisplayGroupController@qTest');
    Route::get('question/display-groups/{displayGroup}', 'DisplayGroupController@qTest');
    Route::get('answer/display-groups/{displayGroup}', 'DisplayGroupController@qTest2');
    Route::get('display-groups/question/{question}', 'DisplayGroupController@qTest3');
    Route::get('display-groups/answer/{answer}', 'DisplayGroupController@qTest4');
    #combinations
    Route::resource('combinations', 'CombinationsController');

    #Ready procedures
    Route::put('ready-procedures/{procedure}', 'ReadyProceduresController@update')->name('ready-procedures.update');

    #User
    Route::resource('users', 'UsersController');
    Route::get('supervisor', 'UsersController@supervisor');
    #Users Roles
    Route::get('user-roles/{user}/edit', 'UserRolesController@edit')->name('user-roles.edit');
    Route::patch('user-roles/{user}', 'UserRolesController@update')->name('user-roles.update');

    #Users Procedures
    Route::get('users-procedures/{user}/edit', 'UsersProceduresController@edit')->name('users-procedures.edit');
    Route::patch('users-procedures/{user}', 'UsersProceduresController@update')->name('users-procedures.update');

    #Roles
    Route::get('roles', 'RolesController@init');
    Route::get('roles/index', 'RolesController@index');
    Route::post('roles', 'RolesController@store');
    Route::post('roles/{role}/update', 'RolesController@update');
    Route::post('roles/{role}/delete', 'RolesController@destroy');

    #Categories
    Route::resource('categories', 'CategoriesController');

    #procedureScores
    Route::get('procedure-scores/{procedure}', 'ProcedureScoresController@index')->name('procedure-scores.index');
    Route::get('procedure-scores/{score}/edit', 'ProcedureScoresController@edit')->name('procedure-scores.edit');
    Route::put('procedure-scores/{score}', 'ProcedureScoresController@update')->name('procedure-scores.update');
    Route::delete('procedure-scores/{score}', 'ProcedureScoresController@destroy')->name('procedure-scores.destroy');

    #Procedures
    Route::post('duplicate-procedure/{procedure}', 'DuplicateProcedureController@create')->name('procedures.duplicate');
    Route::get('api/procedures/api/create', 'ProceduresController@create');
    Route::resource('api/procedures', 'ProceduresController', ['except' => ['index']]);

    #Decisions
    Route::resource('decisions', 'DecisionsController');

    #Statistics
    Route::get('statistics', 'StatisticsController@index');

    #Client Parameters
    //Route::put('client-params/{param}', 'ClientParamsController@update')->name('go123.update');
    //Route::put('client-params', 'ClientParamsController@update')->name('client-params.update');
    Route::resource('client-params', 'ClientParametersController');

    #Params
    Route::resource('params', 'ParamsController');

    #Answer Params
    Route::post('display-group/{question_id}', 'AnswerParamsController@answersParamsSameGroups');
    Route::post('display-group/multi-labels/update/{display_groups}', 'AnswerParamsController@updateAnswersMultiLabels');
    Route::post('answer-params/{answer}', 'AnswerParamsController@update')->name('answer-params.update');
    Route::resource('answer-params', 'AnswerParamsController', ['except' => 'update']);

    #Questions
    Route::get('questions/{proc_id}', 'QuestionsController@init')->name('questions.init');

    #Notes
    Route::resource('notes', 'NotesController');

    #Reports
    Route::resource('reports', 'ReportsController');

    #Language
    Route::get('languages/{language}', 'LanguagesController@update')->name('languages.update');

    #Conflicts
    Route::get('conflicts/{procedure}', 'ConflictsController@index');
    Route::post('conflicts/{conflict}/delete', 'ConflictsController@destroy');

    Route::group(['prefix' => 'api'], function () {

        #Procedure
        Route::get('procedure/{proc_id}/title', 'ProceduresController@getTitle');
        Route::get('procedure/publish/{procedure}', 'ProceduresController@publish');
 


        #questions
        Route::get('questions/tags/{source}', 'QuestionsController@getTagsData');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Client
 *
 * @package App
 * @property int $id
 * @property \Carbon\Carbon|null $updated_at
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon|null $deleted_at
 * @property string $client_name
 * @property string $created
 * @property string $modified
 * @property bool $is_deleted
 * @property string $client_code
 * @property string $send_report_emails
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\CombinationInstance[] $combinationInstances
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Combination[] $combinations
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Parameter[] $params
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Test[] $tests
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\User[] $users
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Query\Builder|\App\Client onlyTrashed()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereClientCode($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereClientName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereCreated($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereIsDeleted($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereModified($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereSendReportEmails($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Client withTrashed()
 * @method static \Illuminate\Database\Query\Builder|\App\Client withoutTrashed()
 * @mixin \Eloquent
 */
class Client extends Model {
    
    use SoftDeletes;
    
    /**
     * @var array
     */
    protected $dates = ['deleted_at'];
    
    /**
     * @var array
     */
    protected $fillable = [
        'client_name',
        'client_code',
        'send_reports_email',
    ];
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function users()
    {
        return $this->hasMany(User::class);
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function params()
    {
        return $this->hasMany(Parameter::class);
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function combinations()
    {
        return $this->hasMany(Combination::class);
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function combinationInstances()
    {
        return $this->hasMany(CombinationInstance::class);
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasManyThrough
     */
    public function tests()
    {
        return $this->hasManyThrough(Test::class, CombinationInstance::class);
    }
    
    public static function list()
    {
        return static::all()->keyBy('id')->map->client_name;
    }
}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Client;

/**
 * Class ClientsController
 * @package App\Http\Controllers
 */
class ClientsController extends Controller {
    
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $clients = Client::all();
        
        return view('client.index', compact('clients'));
    }
    
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('client.create');
    }
    
    /**
     * @param Request $request
     *
     * @return $this|\Illuminate\Database\Eloquent\Model
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'client_name' => 'required|min:2|max:100',
            'client_code' => 'required|min:2|max:100',
        ]);
        
        return Client::create([
            'client_name'        => request('client_name'),
            'client_code'        => request('client_code'),
            'send_report_emails' => request('send_report_emails'),
        ]);
    }
    
    /**
     * @param Client $client
     */
    public function show(Client $client)
    {
        //
    }
    
    /**
     * @param Client $client
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Client $client)
    {
        return view('client.edit', compact('client'));
    }
    
    /**
     * @param Request $request
     * @param Client  $client
     *
     * @return Client
     */
    public function update(Request $request, Client $client)
    {
        $this->validate($request, [
            'client_name' => 'required|min:2|max:100',
            'client_code' => 'required|min:2|max:100',
        ]);
        
        $client->update([
            'client_name'        => request('client_name'),
            'client_code'        => request('client_code'),
            'send_report_emails' => request('send_report_emails'),
        ]);
        
        return $client;
    }
    
    /**
     * @param Client $client
     */
    public function destroy(Client $client)
    {
        $client->delete();
    }
}

resources/views/client/create.blade.php
<div class = "modal-header">
    <button type = "button" class = "close" data-dismiss = "modal" aria-label = "Close"><span
                aria-hidden = "true">&times;</span>
    </button>
    <h4 class = "modal-title">Add Client</h4>
</div>
<div class = "modal-body">
    {!! Form::open(['route' => 'clients.store','class' => 'bootstrap-modal-form']) !!}

    <div class = "form-group">
        {!! Form::label('client_name','Client Name') !!}
        {!! Form::text('client_name',null,['class' => 'form-control']) !!}
    </div>
    <div class = "form-group">
        {!! Form::label('client_code','Client Code') !!}
        {!! Form::text('client_code',null,['class' => 'form-control']) !!}
    </div>
    <div class = "form-group">
        {!! Form::label('send_report_emails','Reports E-mail List') !!}
        {!! Form::text('send_report_emails',null,['class' => 'form-control']) !!}
    </div>
</div>
<div class = "modal-footer">
    <button type = "button" class = "btn btn-default" data-dismiss = "modal">Close</button>
    <button type = "submit" title = "Congratulations!" data-content = "New Client has been created successfully."
            data-animation = "true"
            data-placement = "left" class = "btn btn-primary bootstrap-modal-submit">Create
    </button>
    {!! Form::close() !!}
</div>

resources/views/client/edit.blade.php
<div class = "modal-header">
    <button type = "button" class = "close" data-dismiss = "modal" aria-label = "Close"><span
                aria-hidden = "true">&times;</span>
    </button>
    <h4 class = "modal-title">Update Client</h4>
</div>
<div class = "modal-body">
    {!! Form::model($client, ['route' => ['clients.update', $client->id],'class' => 'bootstrap-modal-form','method' => 'put']) !!}
    <div class = "form-group">
        {!! Form::label('client_name','Client Name') !!}
        {!! Form::text('client_name',$client->client_name,['class' => 'form-control']) !!}
    </div>
    <div class = "form-group">
        {!! Form::label('client_code','Client Code') !!}
        {!! Form::text('client_code',$client->client_code,['class' => 'form-control']) !!}
    </div>
    <div class = "form-group">
        {!! Form::label('send_report_emails','Reports E-mail List') !!}
        {!! Form::text('send_report_emails',$client->send_report_emails,['class' => 'form-control']) !!}
    </div>
</div>
<div class = "modal-footer">
    <button type = "button" class = "btn btn-default" data-dismiss = "modal">Close</button>
    <button type = "submit" title = "Congratulations!" data-content = "Client has been updated successfully."
            data-animation = "true"
            data-placement = "left" class = "btn btn-primary bootstrap-modal-submit">Update
    </button>
    {!! Form::close() !!}
</div>

resources/views/client/index.blade.php
@extends('master')

@section('title', 'Clients')

@section('content')
    <!-- page content -->
    <div class = "right_col" role = "main">
        <div class = "container">
            <table class = "table text-center clients-table table-striped table-bordered nowrap" style = "display: none"
                   cellspacing = "0" width = "100%">
                <thead>
                <tr>
                    <th class = "text-center">Id</th>
                    <th class = "text-center">Name</th>
                    <th class = "text-center">Code</th>
                    <th class = "text-center">Reports e-mail list</th>
                    <th class = "text-center noExport">Actions</th>
                </tr>
                </thead>
                <tbody>
                @if(isset($clients))
                    @foreach($clients as $client)
                        <tr>
                            <td>{{$client->id}}</td>
                            <td>{{$client->client_name}}</td>
                            <td>{{$client->client_code}}</td>
                            <td>{{$client->send_report_emails}}</td>
                            <td>
                                <div class = "btn-group btn-group-sm">
                                    <button style = "color: #73879C"
                                            class = "edit-registry btn btn-default bootstrap-modal-form-open"
                                            data-url = "{{route('clients.edit', $client->id)}}"><i
                                                class = "far fa-edit" aria-hidden = "true"></i> Edit
                                    </button>
                                    <button style = "color: #73879C" token = "{{csrf_token()}}"
                                            url = "{{route('clients.destroy', $client->id)}}" href = "#"
                                            class = "btn btn-default delete-confirm">
                                        <i class = "far fa-trash-alt"
                                           aria-hidden = "true"></i> Delete
                                    </button>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
        </div>
    </div>
    <!-- /page content -->
    @include('components.modal')
@endsection

@section('script')
    <script src = "{{asset('js/clients.js')}}"></script>
@endsection